language: ruby

cache: bundler

before_install:
  # "yes" is a workaround for https://github.com/rubygems/rubygems/issues/3030
  - yes | travis_retry gem update --system
  - travis_retry gem install bundler -v "<2"
